### ISSUE TITLE
Top shield - gaps

### ISSUE THREAD

**Issue by graiz** [Cederb/Faceshield.nu#12]
I got feedback from one of the hospitals that I'm working with that they would like to eliminate the gap/hole between the mask edge and the face. 

I made a variation that looks like this:
https://imgur.com/PjLiYEI

Note a 1/2mm gap to allow the arm to continue to flex. 
https://imgur.com/jJZd2q8

For hospitals that aren't using the top-shield, it provides some additional shielding from the downward spray.  Happy to provide the reference designs if needed.

**Comment by Sarashorin** [comment]
Would love the design link to fill in the gaps.  Thanks so much!!! Looks good!!! Sarashorin@gmail.com

**Comment by Sarashorin** [comment]
I agree, hospitals want to fill the gap

**Comment by graiz** [comment]
I have my draft STL here. I prefer not to fork the core design hosted here. If this issue gets resolved I would prefer to delete my version. https://www.thingiverse.com/thing:4257419

**Comment by Cederb** [comment]
Even like what you have done now, you joined the curves and removed more than half of the flex in the front, making it fit less well on a wide range of head sizes, especially with stiff filaments like PLA. 

You also introduced a thin plane that have a edge right into the forehead that will be much more fragile, and by trying to fill the curve all the way to the radius of the plastic shield , you reduced the allowed tolerance for misplaced holes by quite a bit.

I do not see this as a universal improvement and there is a very thin line between how much to cover up vs how robust the design is for different materials and low printing tolerances. We have some people pushing these out with 1mm+ nozzles in ten minutes, and then there is no such thing there as a 0.5mm slot.

**Comment by Cederb** [comment]
This whole red marked section is acting as the spring to let it conform to a wide range of head sizes, not just the arm:
![image](https://user-images.githubusercontent.com/8168818/78311526-61b0d100-7551-11ea-98e5-9c448e9032d8.png)

**Comment by graiz** [comment]
Yes. That's why I'm calling my design a draft.  I don't have the original files so I was just mesh editing. This issue is a request to modify the original design with my image as a reference in terms of what I'm describing. My design doesn't flex as well as the original.

**Comment by Cederb** [comment]
I have tried making it more closed in multiple revisions, and it is honestly not that easy without making it flex way less or become very tightly tolerance dependent on the printing.

And what i mean with the front curve is that the shield plastic should be able to sit either like the line on the right or the one on the left to take up differences in hole placements.
![image](https://user-images.githubusercontent.com/8168818/78311759-fddad800-7551-11ea-8177-666e87c65c28.png)

**Comment by Sarashorin** [comment]
Thank you so much!!! Much appreciated!!

Be well, stay well!
Sara

**Comment by graiz** [comment]
@Cederb  - I was able to get it to flex reasonably by adding a few cuts to three places.  I'm printing with a 0.4mm nozzle and it hasn't been an issue because the printer still positions at sub-mm precision. It just can't extrude a very thin line but it doesn't have a problem keeping inside of this. I added three features.   1. Inner bend cut.  2. Outer bend cut. 3. Added arm flex. 

I've shown what my draft looks like. Printing now.  https://imgur.com/a/aR66yln 

Even assuming either the flex of your right or left version you still have top-down gaps that could be filled. I understand what you're describing with the two different profiles based on the transparency and the hole placement.

**Comment by Cederb** [comment]
@graiz - As i said, one of my design goals is for the design to be extremely robust and tolerant to printing tolerances, 0.5mm slots is not a thing that matches that goal.

Your added arm flex does increase printing time, reduces the possibility to print well with larger nozzles, and it also makes it harder to wipe to clean/disinfect. Every feature i include has to be printable with at least 0.8mm nozzle size, preferably 1mm, and as much as possible just with continous outlines, this is why all the things in the design share specific dimensions to make it able to be a multiple of the line width.

**Comment by gregsvo** [comment]
I created a fork with the top covers that maintains the flexibility of the visors: https://github.com/gregsvo/Faceshield.nu/tree/master/north_america_6_hole_improved

The version I edited are the north-american 6-hole version, but on my fork I included step, stl, and fusion 360 for your own editing.

I have a single extruder and was frustrated at only making a single visor at a time, so now they print as three units, and a single drop of superglue holds the arms in their locking mechanism. @Cederb @graiz @Sarashorin

**Comment by graiz** [comment]
Looks great. Trying to print this soon.  A side benefit of this approach is that I can get more masks on the build plate per print.   https://imgur.com/a/9uN6O6r
Your visor design looks much better too.   Thank you!  If I can buy you a roll or two of filament, send me your venmo.

**Comment by graiz** [comment]
FYI:  I printed the design and it works well but I don't like the parts falling out so easily because of tolerances.  I added a simple sphere snap-fit on both parts to allow the parts to snap and hold together.  Using a 2.2mm sphere and trying this now.  https://imgur.com/a/22vaq8B.

**Comment by gregsvo** [comment]
@graiz I love that. Yeah I was just puting a drop of super glue to hold them in, but snap-fit is obviously a better solution. I appreciate the offer for filament! But I was given a couple of rolls and I've got more than enough. Keep up the fight!!!!

**Comment by graiz** [comment]
FYI - Snap-fit printed without issue / no supports and the fit does snap-in at the current tolerances and does not come out easily. I was able to remove the arms but they are in there pretty tight.

**Comment by JDU1** [comment]
tried to fix the problem, maybe someone wants to test it? the load is not too great. i also increased the distance from the forehead to the window, otherwise big noses would bump.

Visor_frame_EUROPE_80mm

[top_shield_v2_no_gap.zip](https://github.com/Cederb/Faceshield.nu/files/4447171/top_shield_v2_no_gap.zip)


![image](https://user-images.githubusercontent.com/32439899/78722903-aca05f00-792a-11ea-9137-aab5b3333651.png)
![image](https://user-images.githubusercontent.com/32439899/78722906-b0cc7c80-792a-11ea-9ad8-871abfa47cba.png)

**Comment by graiz** [comment]
@gregsvo  - I'm going to close this issue.  The fork you provided resolves the original issue I opened. I'm happy to provide the snap-fit edit if you'd like it and I'll leave it to you to either keep the forked branch or choose to merge it at some point.   Thanks.
