### ISSUE TITLE
Chamfer the top edge PLEASE!

### ISSUE THREAD

**Issue by dbfrompw** [Cederb/Faceshield.nu#18]
By putting a chamfer the top edge of the model, it will come out much better and be easier to print. less touch-up work after the print, nobody likes a sharp edged part.  And a Step file would be nice!

Thank you.

**Comment by Cederb** [comment]
Chamfered edges does interfere with the slicer algorithms when slicing for large nozzles, making it very hard to get a solid part with only perimeters. This is why it is intentionally left sharp.

**Comment by dbfrompw** [comment]
Bummer. I only have a .4 nozzle and have to hand work that top edge.

**Comment by dbfrompw** [comment]
> 
> 
> Chamfered edges does interfere with the slicer algorithms when slicing for large nozzles, making it very hard to get a solid part with only perimeters. This is why it is intentionally left sharp.

could I talk you out of the step file?

**Comment by Cederb** [comment]
Send me a email at faceshield@3dverkstan.se. Not going to publish it openly since some people have been blatantly ignoring licenses and sharing the design with no attribution, claiming they created it, and being asses about it.
