### ISSUE TITLE
there are no 80mm between the centrale hole on V3

### ISSUE THREAD

**Issue by gaelalso** [Cederb/Faceshield.nu#4]
Hi, thanks you for your job,
there are no 80mm between the centrale hole on V3 ISO838
on v1 it's ok.

there are a reason?

**Comment by Cederb** [comment]
ISO838 versions is made to accomodate the standard 80mm 2-hole punch, set to A6 format and punched once on either side, this gives a center distance of closer to 68mm than 80mm.
