### ISSUE TITLE
Pegs too big for hole punch

### ISSUE THREAD

**Issue by indyjason79** [Cederb/Faceshield.nu#7]
First off, thank you for making these! On the North American version the pegs are larger (elliptical instead of circular). I'm having to double punch the same hole twice to make it fit which is making some of the shields fall off the visor. Why was this done differently and can we get a North American version with round pegs like the other versions please? I need to print hundreds of these and it's going to screw things up if I have to double punch all the holes.

**Comment by Cederb** [comment]
Hi 

The North american hole punches does not have a very tightly defined standard, with holes allowed to be anything between 1/4" and 5/16", with many trending towards the larger, so the pegs were made to allow for the larger size of the hole punches in common use.

**Comment by indyjason79** [comment]
Thanks for the clarification. Maybe it's because I'm using a single hand hole punch instead of a desk version. I'm going to see if I can find someone with a desk hole punch and hopefully this won't be an issue anymore.

**Comment by indyjason79** [comment]
FYI, someone created a stackable version of your model. You may want to add it to your zip on your website. https://www.thingiverse.com/thing:4247264

**Comment by Cederb** [comment]
About the stacking, see: https://github.com/Cederb/Faceshield.nu/pull/5

**Comment by indyjason79** [comment]
After switching to a desktop version of a 3 hole punch machine this isn't an issue anymore. It was just the hand-held hole punch that didn't make the holes big enough.
