### ISSUE TITLE
Transparent plastic sheet detach

### ISSUE THREAD

**Issue by GuillaumeSTEIN** [Cederb/Faceshield.nu#8]
Hi,

I printed the Visor_frame_EUROPE_80mm_4hole_v1.stl file and the holes are well aligned.
But the transparent sheet is too loose and easily get off the structure.
Here is a video to illustrate it : https://www.youtube.com/watch?v=HHXnbsCBFrk

I'm thinking about printing it to 101% or more to make it more rigid.
Or maybe a ring to lock the sheet

Do you have any idea ?

**Comment by Cederb** [comment]
Ok, got this feedback from a few more comments, will update that version with a slightly tighter fit.

**Comment by GuillaumeSTEIN** [comment]
Ok I now print it in 101%, it fixed my issue.
More % will deform the holes.

**Comment by Cederb** [comment]
The latest version pushed has 1mm tighter spacing for the holes on the EU 80mm version.
