### ISSUE TITLE
DXF File request for Visor_frame_EUROPE_ISO838_v3.stl

### ISSUE THREAD

**Issue by motu81** [Cederb/Faceshield.nu#9]
could you please upload the 3D Model if this STL File?

**Comment by Cederb** [comment]
Hi

Not planning on doing that at the moment.

Already had multiple people claiming the design as their own and a lot of people not care at all about the license, so don't want to support people even more doing that.

Everyone that has a good enough reason will get a STEP file if they email me at faceshield@3dverkstan.se
